### PR TITLE
Dawntrail and 7.1 Update

### PR DESCRIPTION
**Pull request by KangasZ**
Updates to support the new patch.

### CODE REVIEW

**Comment by Infiziert90** [comment]
Needs to be updated again, CS enabled the obsoletes to error on compile now :)

**Comment by KangasZ** [comment]
Of course, well It's updated. Thanks for bringing it up.

**Comment by ascobolonline** [comment]
Hey there, thanks for updating it.. is Api10 latest or is it Api11 by now?

**Comment by KangasZ** [comment]
This targets API11.

**Comment by ascobolonline** [comment]
> This targets API11.

Just thought I asked, as the commit comments stated Api10 :)

**Comment by KangasZ** [comment]
I am closing this PR with the intent to take ownership temporarily for the official distribution of EurekaHelper

**Pull request closed without merging**
