### PR TITLE
API 10 + DT Update

### PR DESCRIPTION
**Pull request by KangasZ**
Hello, updating this since I did it for personal use and figured it might be helpful.

Couple notes:

- `ECommons` replacing `XivCommon`. This is due to the `ECommons.Automation.Chat` module being functionally identical to XivCommon and XivCommon has not been updated to my knowledge
- Previous `SoundManager` (with a manual sig) instead just uses `FFXIVClientStructs.UIModule`. Existing one just would crash the game
- Net 8.0 Update
- API 10 Update

### CODE REVIEW

**Comment by snorux** [comment]
Thank you. I'll take a look at this.

**Comment by snorux** [comment]
Honestly would prefer not to use ECommons due to it having alot more modules than we need, would it be possible to pull the Chat module in XivCommons to the plugin instead?

**Comment by KangasZ** [comment]
Updated, pulled out ECommons in favor of just the Chat class

**Comment by SaengerItsWar** [comment]
xivcommon got updated on end of july. https://git.anna.lgbt/anna/XivCommon

**Comment by KangasZ** [comment]
Not going to do any more work on this atm. Good to know, though.

**Pull request closed without merging**
